#PS1="[\w] λ "
PS1="\n\w λ "

# MacPorts Installer addition on 2011-04-11_at_16:48:02: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# brew
export PATH=/usr/local/bin:$PATH

# npm
export PATH=/usr/local/share/npm/bin:$PATH

# mysql
export PATH=/usr/local/mysql/bin:$PATH

# Go
mkdir -p ${HOME}/code/GOPATH-global
export GOPATH=${HOME}/code/GOPATH-global
export PATH=${PATH}:/usr/local/go/bin
export PATH=${PATH}:${GOPATH}/bin
# if this doesn't work long term:
# "setenv GOPATH $HOME/code/GOPATH-global" in /etc/launchd.conf

# Mine
export PATH=${PATH}:~/code/marcuswestin/dotfiles/bin
alias d="cd ~/code/dogo"
alias i="cd ~/code/ivyq"
alias f="cd ~/code/dogo/src/go/src/github.com/marcuswestin/fun"
alias p="cd ~/code/secrets/Pen\ and\ Paper"
alias s="cd ~/code/surlei"
alias glog="git log --format='%Cgreen%h%Creset %C(cyan)%an%Creset - %s' --graph"
alias t="make test"
alias saga="subl ~/Dropbox/Saga.md"
