# Prompt
PS1="\n\w λ "

# Brew
export PATH=/usr/local/bin:$PATH

# MacPorts Installer addition on 2011-04-11_at_16:48:02: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# Mine
######
export PATH=${PATH}:~/code/marcuswestin/dotfiles/bin
alias d="cd ~/code/dogo"
alias i="cd ~/code/ivyq"
alias p="cd ~/code/secrets/Pen\ and\ Paper"
alias glog="git log --format='%Cgreen%h%Creset %C(cyan)%an%Creset - %s' --graph"
alias t="make test"
alias saga="subl ~/Dropbox/Saga.md"
alias a=asapp
alias s=stackack
alias f=allform
alias bell="echo $'\a' '*** BELL ***'"

# AllForm stuff
alias allform="cd /Users/marcus/code/allform && source misc/automate/source-dev.sh"

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# ASAPP stuff
alias asapp="cd /Users/marcus/code/asapp && source misc/source-asapp-dev.sh"
  
# STACKACK
alias stackack="cd /Users/marcus/code/stackack && source scripts/dev/automate-dev-env/source-dev.sh"


# AMZNMATE
alias amznmate="cd /Users/marcus/code/amzn-mate && source scripts/dev/automate-dev-env/source-dev.sh"

