#PS1="[\w] λ "
PS1="\n λ "

# MacPorts Installer addition on 2011-04-11_at_16:48:02: adding an appropriate PATH variable for use with MacPorts.
#export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# brew
export PATH=/usr/local/bin:$PATH

# mysql
export PATH=/usr/local/mysql/bin:$PATH

# code swarm
export PATH=/Users/marcus/code/others/code_swarm/bin:$PATH

# Android
export PATH=${PATH}:/Applications/android-sdk-mac_x86/tools
export PATH=${PATH}:/Applications/android-sdk-mac_x86/platform-tools

# Go
export PATH=${PATH}:/usr/local/go/bin

# Mine
export PATH=${PATH}:~/code/marcuswestin/dotfiles/bin

