#PS1="[\w] λ "
PS1="\n\w λ "

# MacPorts Installer addition on 2011-04-11_at_16:48:02: adding an appropriate PATH variable for use with MacPorts.
#export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# brew
export PATH=/usr/local/bin:$PATH

# mysql
export PATH=/usr/local/mysql/bin:$PATH

# Android
export PATH=${PATH}:~/bin

# Go
export PATH=${PATH}:/usr/local/go/bin

# Mine
export PATH=${PATH}:~/code/marcuswestin/dotfiles/bin
alias d="cd ~/code/dogo"
alias glog="git log --format='%Cgreen%h%Creset %C(cyan)%an%Creset - %s' --graph"
alias t="make test"
alias s="subl ~/saga/README.md"
